// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZuteDy1QJkf5MO2M-P5QKS96Hnw8e0dk',
    appId: '1:949760014121:web:21d7632698121a7fc76938',
    messagingSenderId: '949760014121',
    projectId: 'finalnotify-55443',
    authDomain: 'finalnotify-55443.firebaseapp.com',
    storageBucket: 'finalnotify-55443.appspot.com',
    measurementId: 'G-R5070XJHD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aqlesThKTziUvsnGiBZwVIWkxv78F9s',
    appId: '1:949760014121:android:76abc74cd8ec5913c76938',
    messagingSenderId: '949760014121',
    projectId: 'finalnotify-55443',
    storageBucket: 'finalnotify-55443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEe5YuPIQgrcmCkI5r2SoGcr0JiJ2e7Ls',
    appId: '1:949760014121:ios:b459f38e97559958c76938',
    messagingSenderId: '949760014121',
    projectId: 'finalnotify-55443',
    storageBucket: 'finalnotify-55443.appspot.com',
    iosBundleId: 'com.example.finalnotify',
  );
}
